### ISSUE TITLE
Compatibility with Docker ENV files

### ISSUE THREAD

**Issue by fireproofsocks** [fireproofsocks/dotenvy#15]
It could be very useful if the `.env` files used a format that can also be used by docker. 

```
docker run --env-file
```

https://docs.docker.com/compose/env-file/

MOST of the stuff is the same... but the triple-quoted strings that the `dotenvy` parser supports probably won't work if docker attempted to parse them.

**Comment by nelsonmestevao** [comment]
By triple-quoted strings, you mean multi-line variables?

### example

```
VAR="""
The long message text for something.
It can be across multiple lines.
"""
```

**Comment by fireproofsocks** [comment]
Yes, exactly -- the triple-quoted multi-line variables are more of an Elixir thing than a .env thing.  I think I'll probably have to settle for the fact that not everyone's interpretation of a .env file will be the same.

**Comment by nelsonmestevao** [comment]
Well I have seen env files with multiple lines. Special SSH keys 👀

**Comment by fireproofsocks** [comment]
I feel like I've seen that too.   E.g. https://stackoverflow.com/questions/56475228/using-multi-line-value-in-env-file-in-docker-compose or https://stackoverflow.com/questions/46147228/dotenv-multiline-variables ... But I haven't see the triple-quotes.  Do you have other examples?

**Comment by nelsonmestevao** [comment]
I think I remember seeing it in Java projects. 

At least, it works on bash and zsh:

![image](https://github.com/fireproofsocks/dotenvy/assets/19409687/61745966-6013-4924-9096-8be25eea7e19)


And the difference between """ and ''' seems to be if you want to expand variables inside or not.

**Comment by fireproofsocks** [comment]
Interesting!  Thanks for sharing that.  Maybe this stuff is already supported 🤔

**Comment by nelsonmestevao** [comment]
It does work :joy: @fireproofsocks

**Comment by fireproofsocks** [comment]
Sweet!  Closing this :)

**Comment by nelsonmestevao** [comment]
I added a PR with tests for this functionality: https://github.com/fireproofsocks/dotenvy/pull/19
