### ISSUE TITLE
relative path in release computed wrt CWD and not wrt release  

### ISSUE THREAD

**Issue by starkeepers** [fireproofsocks/dotenvy#3]
When a release is built with a relative path for the env file, as in:

`source!("../data/.env")`

the file is found when starting the release with `./bin/myapp start` but not when starting with `./foo/bin/myapp start` -- ie it seems dependent on the CWD of the caller. Ideally, the files should be relative to the script doing the searching, as in bash's $0.

**Comment by fireproofsocks** [comment]
Yes, it is is dependent on where things get called.  This article should assist: https://fireproofsocks.medium.com/using-dotenvy-in-elixir-releases-68e566c0bf9f

**Comment by starkeepers** [comment]
That page is behind a `Read the rest of this story with a free account`, maybe it can be documented somewhere accessible to everyone? At any rate, the implicit feature request was to have it relative to the executing script rather than relative to the caller, which would make the system more predictable and reproduceable -- but of course, not a big deal at all and feel free to ignore it. And thanks for dotenvy, it is very nice :)

**Comment by fireproofsocks** [comment]
The gist of the article is that you can provide an absolute path manually (It didn't feel appropriate to have `dotenvy` try to resolve that).  The article links to a sample implementation at https://github.com/fireproofsocks/mermaid-demo

The `runtime.exs` includes:
```
config_dir_prefix =
  System.fetch_env("RELEASE_ROOT")
  |> case do
    :error ->
      "envs/"

    {:ok, value} ->
      IO.puts("Loading dotenv files from #{value}")
      "#{value}/"
  end

source!([
  "#{config_dir_prefix}.env",
  "#{config_dir_prefix}.#{config_env()}.env",
  "#{config_dir_prefix}.#{config_env()}.local.env"
])
```
and you can force your releases to "overlay" the contents of a directory by specifying the `overlays` option in your `mix.exs` e.g. if your app is named `myapp` and your env files are inside a sub-folder named `envs/`, then you could do:

```
  defp releases do
    [
      myapp: [
        overlays: ["envs/"]
      ]
    ]
  end
```

Let me know if that works for you!

**Comment by starkeepers** [comment]
> It didn't feel appropriate to have dotenvy try to resolve that

Fair enough (I still feel that a predictable default would be better than a caller-dependent default, but of course it is your judgement call here). And thanks for the workaround, that works for me :)

**Comment by fireproofsocks** [comment]
Glad that worked for you.  Since other packages and Elixir itself don't seem to take a stand on how or where you execute code, I figured that probably would be out of scope for this package as well.  

You can always sign up for a free Medium account to read articles there -- there's a fair amount of Elixir articles in there of late (including some of my own).

**Comment by starkeepers** [comment]
> other packages and Elixir itself don't seem to take a stand on how or where you execute code

Note that it is really not about "taking a stand on how or where you execute code", as much as making it irrelevant how or where you execute code (because relative paths would be computed wrt the release, as opposed to wrt the caller), hence making the system more predictable/reproduceable.

**Comment by fireproofsocks** [comment]
I'm all for making things more predictable -- so far the best solutions I came up with was using the `overlays` option or to put the envs into some directory that would get included by default in the release build.  If there's something more elegant I'm all for it!
