### ISSUE TITLE
Integer casting is not properly caught

### ISSUE THREAD

**Issue by lud** [fireproofsocks/dotenvy#5]
```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a textual representation of an integer

    :erlang.binary_to_integer("HAHA")
```

I can submit a PR if you agree with my strategy: only wrap the `to!` call in a try/rescue, and add `when is_binary(variable)` to the env!/ functions.

**Comment by fireproofsocks** [comment]
To reproduce the behavior under discussion:
```
iex> Dotenvy.Transformer.to!("HAHAHA", :integer)
** (ArgumentError) argument error
    :erlang.binary_to_integer("HAHAHA")
    (dotenvy 0.3.0) lib/dotenvy/transformer.ex:137: Dotenvy.Transformer.to!/2
```

Actually, looking at this, I think the existing behavior is plausibly "correct" (ish): if the value provided cannot be parsed into an integer, then attention should be drawn to that fact (e.g. an error raised), otherwise you might not realize that the provided value isn't sensible.  This is why the function name is `to!` and not `to`.

Thoughts to consider: `to!(val, :integer)` provides a default value of `0` when an empty string is encountered, so the question here is whether an un-parsable string should also return `0`.  I seem to remember that PHP treats all strings as zeroes if they are cast to integers, so there is a precedent out there for doing this (at least in PHP).

I think there are 2 possible options here:

1. Leave the implementation as is: use the custom callback (available in v0.4.0) to handle use cases that are not supported out of the box.

OR

2. Modify the `:integer` and `:float` types to leverage `Integer.parse/2` and `Float.parse/2` functions and return `0` when ANY un-parsable value is encountered.  The `:integer!` and `:float!` types could still raise on un-parsable errors.  (The distinction between `:integer` and `:integer!` does start to get a bit meta with this option).

Thoughts?

**Comment by lud** [comment]
Indeed:

```
php > var_dump((int) 'hello');
int(0)

iex(1)> String.to_integer "hello"
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a textual representation of an integer

    :erlang.binary_to_integer("hello")

```

PHP's behaviour is really bad I think. It cannot be trusted. Environment variables are sensible data for an application, we cannot loosely and silently default to an int. `0` is not even falsy in Elixir. Plus, they are given by devs or admins, it is ok to crash early and not try to cope automatically.

The main problem is that the error is not explicit. When you call directly from the transformers module you can easily understand where is the problem.

When you run the runtime.exs file on the other hand, this is what you get when `env!` fails:

```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a textual representation of an integer

    :erlang.binary_to_integer("AAAAAA")
    (dotenvy 0.3.0) lib/dotenvy/transformer.ex:129: Dotenvy.Transformer.to!/2
    (dotenvy 0.3.0) lib/dotenvy.ex:107: Dotenvy.env!/2
    (stdlib 3.15) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.1) lib/code.ex:656: Code.eval_string_with_error_handling/3
    (elixir 1.12.1) lib/config.ex:258: Config.__eval__!/3
    (elixir 1.12.1) lib/config/reader.ex:86: Config.Reader.read!/2
    (mix 1.12.1) lib/mix/tasks/loadconfig.ex:57: Mix.Tasks.Loadconfig.load_runtime/1

```

You cannot see where is the problem, you only see the value, and as you were expecting an integer, a non-numeric string gives little clues about what variable is in guilt. Plus, maybe a sysadmin will see it, not a dev, and they can only provide a better value, but they will need the variable name.

Now I have incidentally forgot to put the `!` to `env` and got this error. This is good because you see the variable name.

```
** (RuntimeError) Error converting STUFF to integer: errors were found at the given arguments:

  * 1st argument: not a textual representation of an integer

    :erlang.binary_to_integer("AAAAA")
```

Reading the code I couldn't understand why I saw that, so I added some prints in your code and now I cannot see it again :grey_question: :grey_exclamation: .


Anyway, to me the solution is simple: we should just wrap any error to give the context (varname, and even better the file/line of the call in runtime.exs thanks to a macro).

**Comment by lud** [comment]
Also maybe we should hide the value from the error logs in production environments.

**Comment by fireproofsocks** [comment]
This makes sense. Thank you for elaborating.

**Comment by lud** [comment]
You are welcome, this is a nice project!

Using a macro I can successfully print the file/line of the originating call whereas the stack trace is full erlang:

```
ERROR! Config provider Config.Reader failed with:
** (RuntimeError) could not get environment variable VALUE_A at /home/lud/osef/tod/_build/dev/rel/tod/releases/0.1.0/runtime.exs:8: errors were found at the given arguments:

  * 1st argument: not a textual representation of an integer

    :erlang.binary_to_integer("AAAA")
    (dotenvy 0.4.0) lib/dotenvy/transformer.ex:137: Dotenvy.Transformer.to!/2
    (dotenvy 0.4.0) lib/dotenvy.ex:107: Dotenvy.env!/2
    (stdlib 3.15) erl_eval.erl:685: :erl_eval.do_apply/6
    (stdlib 3.15) erl_eval.erl:919: :erl_eval.try_clauses/8
    (stdlib 3.15) erl_eval.erl:893: :erl_eval.expr_list/6
    (stdlib 3.15) erl_eval.erl:408: :erl_eval.expr/5
    (elixir 1.12.1) src/elixir.erl:280: :elixir.recur_eval/3
```

**Comment by fireproofsocks** [comment]
Thanks!  Can you share what you mean by using a macro here to pinpoint the file/line?  I'd like to improve the error messaging if possible.

**Comment by lud** [comment]
Sure.

But first I would sayt that it has many drawbacks !

First you would have to `use Dotenvy` instead of import, so Dotenvy can manage the imports.

Then in the `Dotenvy` module there would be something like that:

```
  defmacro __using__(_) do
    quote do
      import Dotenvy,
        except: [
          env!: 1,
          env!: 2,
          env!: 3
        ]

      require Dotenvy.Macros
      import Dotenvy.Macros, only: :macros
    end
  end
```

And finally we could declare the `Dotenvy.Macros` module that would wrap the errors, display the filename:lline:

```
defmodule Dotenvy.Macros do
  @moduledoc false

  # This could be used to determine if we show the values on errors
  @show_values? Application.compile_env(:dotenvy, show_values)

  defmacro env!(var) do
    quote do
      Dotenvy.Macros._env!(unquote(call_env(__CALLER__)), unquote(var))
    end
  end

  defmacro env!(var, type) do
    quote do
      Dotenvy.Macros._env!(unquote(call_env(__CALLER__)), unquote(var), unquote(type))
    end
  end

  defmacro env!(var, type, default) do
    quote do
      Dotenvy.Macros._env!(
        unquote(call_env(__CALLER__)),
        unquote(var),
        unquote(type),
        unquote(default)
      )
    end
  end

  def _env!(cenv, var, type) when is_binary(var) do
    try do
      Dotenvy.env!(var, type)
    catch
      t, e ->
        path = Path.relative_to(cenv.file, File.cwd!())
        # message = Exception.normalize(t, e, __STACKTRACE__) |> Exception.message()
        raise RuntimeError, "Could not get environment variable #{var} at #{path}:#{cenv.line}"
    end
  end

  defp call_env(env) do
    %{
      module: env.module,
      file: env.file,
      line: env.line,
      show_values?: @show_values?
    }
    |> Macro.escape()
  end
end
```

As you can see it is not a small modification of the code. It would then require to:

- raise a custom `Dotenvy.KeyError` on missing variables
- rename the `Dotenvy.Transformer.Error` to `Dotenvy.ValueError` and suggest in the docs that custom validator functions should raise that on error.
- add a `raw_env!` (bad name) function to the `Dotenvy` module that would keep the logic and not rescue errors, so the Dotenvy module and the macros module could both wrap it to rescue errors.
- In both modules, use the custom errors to display useful information, and raise a generic, non-disclosing information for any other error rescued.

**Comment by fireproofsocks** [comment]
Thank you for this thorough explanation!

**Comment by fireproofsocks** [comment]
I have improved the error messaging with PR #7 -- this isn't anywhere as thorough as your macro solution above, but it should help users identify the source of problematic values: the name of the ENV variable is now included with the error.

**Comment by lud** [comment]
I think it is good enough and keeps the code simple! Thank you.
